// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }





// import type { Metadata } from "next";
// import { VT323, Space_Grotesk, Syne } from "next/font/google";
// import "./globals.css";

// const vt323 = VT323({ 
//   weight: "400", 
//   subsets: ["latin"],
//   variable: "--font-vt323" 
// });

// const grotesk = Space_Grotesk({ 
//   subsets: ["latin"],
//   variable: "--font-grotesk" 
// });

// const syne = Syne({
//   subsets: ["latin"],
//   variable: "--font-syne"
// });

// export const metadata: Metadata = {
//   title: "Innovation Garage",
//   description: "Sanctuary for builders and radical thinkers.",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={`${vt323.variable} ${grotesk.variable} ${syne.variable}`}>
//       <head>
//         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
//       </head>
//       <body className="bg-cyber-black text-warm-white font-display overflow-x-hidden selection:bg-neon-magenta selection:text-white">
//         {/* Global Scanline Overlay */}
//         <div className="fixed inset-0 pointer-events-none z-50 bg-scanlines bg-[length:100%_4px] opacity-20"></div>
//         {children}
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { VT323, Space_Grotesk, Syne, Silkscreen } from "next/font/google"; // Import Silkscreen
import "./globals.css";

const vt323 = VT323({ 
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-vt323" 
});
const grotesk = Space_Grotesk({ 
  subsets: ["latin"],
  variable: "--font-grotesk" 
});
const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne"
});
// Load Silkscreen
const silkscreen = Silkscreen({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-silkscreen"
});

export const metadata: Metadata = {
  title: "Innovation Garage",
  description: "Sanctuary for builders and radical thinkers.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${vt323.variable} ${grotesk.variable} ${syne.variable} ${silkscreen.variable}`}>
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
      </head>
      <body className="bg-background-main text-text-main font-pixel overflow-x-hidden selection:bg-secondary selection:text-white">
        {children}
      </body>
    </html>
  );
}